project:
  type: book
  output-dir: docs

book:
  title: "Bioinformatics"
  reader-mode: true
  site-url: https://wanganlin00.github.io/Bioinformatics/
  repo-url: https://github.com/Wanganlin00/Bioinformatics
  repo-branch: main
  repo-actions: [edit,issue]
  
  chapters:
    - index.qmd
    - upstream_analysis.qmd

    - part: "数据结构与数据库"
      chapters:
        - biodata_structure.qmd
        - annotation_database.qmd
        
        - ExpressionSet.qmd
        - SummarizedExperiment.qmd
        - SingleCellExperiment.qmd
        # - biobroom.qmd

    
    - part: "下游分析"
      chapters:

        - DEGs_Analysis.qmd
        - EnrichmentAnalysis.qmd
        - PseudotimeAnalysis.qmd
        # - eQTL.qmd
        # - GWAS.qmd
        # - WGCNA.qmd
    - part: sca.qmd
    #   chapters: 
    #     - import.qmd
    #     - QC.qmd
    #     - normalization.qmd
    #     - feature_selection.qmd
    #     - DimensionalityReduction.qmd
    #     - Clustering.qmd
    #     - MarkerGeneDetection.qmd
    #     - CellTypeAnnotation.qmd
    #   
    
    
    # - part: "workflow"
    #   chapters: 
    #     - Seurat.qmd
    #     - workflow.qmd
    
    
    
    
execute:
  message: false
  warning: false

toc: true
toc-depth: 4
number-sections: true
number-depth: 4

code-fold: show
code-tools: true
code-link: true
    
knitr:
  opts_chunk: 
    comment: "#>" 
    collapse: TRUE

fig-format: svg

format: 
  html: 
    theme: cosmo
    df-print: kable
    
editor: visual



