# 细胞类型注释

细胞注释一般包括手动注释和自动注释。

1.  **了解样本细胞成分**。如PBMC，包含T细胞、B细胞、单核细胞、粒细胞；肿瘤样本包含肿瘤细胞（肝癌；肝细胞、星形细胞；肺癌：Club细胞、分泌细胞、杯状细胞）、T细胞、B细胞、巨噬细胞、树突状细胞、肥大细胞、上皮细胞、内皮细胞等

2.  **pan-marker 整理**

    -   人类基因通常是全大写（如 `CD3E`）。

    -   小鼠基因通常是首字母大写，其余小写（如 `Cd3e`）

    -   免疫细胞：CD45+, PTPRC

    -   上皮癌：EpCAM+， EPCAM

    -   基质细胞：CD10+, MME, fibro，or CD31+, PECAM1, endo

    +------------------+--------------+----------------------------+--------------------+
    | **免疫细胞分类** | 亚群         | **人类Marker基因**         | **小鼠Marker基因** |
    +==================+==============+============================+====================+
    | 淋巴系           |              |                            |                    |
    +------------------+--------------+----------------------------+--------------------+
    | T细胞            |              | **CD3E, CD4, CD8A**        | Cd3e, Cd4, Cd8a    |
    +------------------+--------------+----------------------------+--------------------+
    |                  | CD4+ T（Th） | Naive CD4+ ：IL7R, CCR7,   |                    |
    |                  |              |                            |                    |
    |                  |              | Memory CD4+：IL7R, S100A4  |                    |
    +------------------+--------------+----------------------------+--------------------+
    |                  | CD8+ T（Tc） | CD8A, GZMK                 |                    |
    +------------------+--------------+----------------------------+--------------------+
    |                  | Treg         | FOXP3                      |                    |
    +------------------+--------------+----------------------------+--------------------+
    |                  | Tex          | TIGIT, LAG3, HAVCR2, PDCD1 |                    |
    +------------------+--------------+----------------------------+--------------------+
    | B细胞            |              | CD19, MS4A1 (CD20), CD79A  | Cd19, Ms4a1        |
    +------------------+--------------+----------------------------+--------------------+
    | NK细胞           |              | NCAM1 (CD56), KLRD1, NKG7  | Ncam1, Klrd1, Nkg7 |
    +------------------+--------------+----------------------------+--------------------+
    |                  |              |                            |                    |
    +------------------+--------------+----------------------------+--------------------+
    | 髓系             |              |                            |                    |
    +------------------+--------------+----------------------------+--------------------+
    | 单核细胞         |              | CD14, FCGR3A (CD16)        | Cd14, Fcgr3a       |
    +------------------+--------------+----------------------------+--------------------+
    |                  | CD14+ Mono   | CD14, LYZ                  |                    |
    +------------------+--------------+----------------------------+--------------------+
    |                  | FCGR3A+ Mono | FCGR3A, MS4A7              |                    |
    +------------------+--------------+----------------------------+--------------------+
    | 巨噬细胞         |              | CD68, CSF1R                | Cd68, Csf1r        |
    +------------------+--------------+----------------------------+--------------------+
    | Platelet         |              | PPBP                       |                    |
    +------------------+--------------+----------------------------+--------------------+
    | 树突细胞         |              | ITGAX (CD11c)              | Itgax              |
    +------------------+--------------+----------------------------+--------------------+
    | 粒细胞           | 中性粒细胞   | ITGAM (CD11b), MPO         | Itgam, Mpo         |
    +------------------+--------------+----------------------------+--------------------+

    +----------------------------------------------------------------+-------------------------------------------------+
    | 来源                                                           | url                                             |
    +================================================================+=================================================+
    | Cellmarker <https://pmc.ncbi.nlm.nih.gov/articles/PMC9825416/> | <http://bio-bigdata.hrbmu.edu.cn/CellMarker> 或 |
    |                                                                |                                                 |
    |                                                                | <http://117.50.127.228/CellMarker/>             |
    +----------------------------------------------------------------+-------------------------------------------------+
    | PanglaoDB                                                      | <https://panglaodb.se/>                         |
    +----------------------------------------------------------------+-------------------------------------------------+
    | Human cell atlas                                               | <https://www.humancellatlas.org/>               |
    +----------------------------------------------------------------+-------------------------------------------------+
    | Mouse Cell Atlas                                               | <https://bis.zju.edu.cn/MCA/>                   |
    +----------------------------------------------------------------+-------------------------------------------------+
    | 已发表的相同样本类型单细胞文章中提取                           | doi                                             |
    +----------------------------------------------------------------+-------------------------------------------------+
    | **K**idney **I**nteractive **T**ranscriptomics                 | <https://www.humphreyslab.com/SingleCell/>      |
    +----------------------------------------------------------------+-------------------------------------------------+

3.  亚群定义：①细胞聚类基础上注释每个cluster；②细胞聚类基础上大类注释+目标细胞sub_cluster分析+亚群聚类③通过marker/生物学功能注释（如[**clusterProfiler**](https://yulab-smu.top/biomedical-knowledge-mining-book/){style="color:red"} **基因本体论 （Gene Ontology，GO） 或京都基因与基因组百科全书 （Kyoto Encyclopedia of Genes and Genomes，KEGG）**）。

```         
T细胞：

a.  按功能：Naive、Tcm（中央记忆 T 细胞）、Tem（效应记忆 T 细胞）、Temra（终末效应记忆再激活 T 细胞）

b.  按状态：静息 T 细胞、活化 T 细胞、耗竭T细胞

c.  按表面抗体：CD4 （Treg、Th1、Th2、Th9、Th17、Tfh）、CD8
```

4.  未知细胞的定义

    i.  直接定义为 unknown
    ii. 根据只在这个cluster高表达（A+ cluster）或不表达（B- cluster）的基因命名
    iii. 根据可视化位置推断，与其他亚群的空间连续性位置（UMAP）

[**Assigning cell types with SingleR**](https://bioconductor.org/books/release/SingleRBook/){style="color:red"}

[SingleR](https://bioconductor.org/packages/3.18/bioc/html/SingleR.html){style="color:red"}是自动注释方法的一种实现，可以被认为是最近邻分类的稳健变体。

```{r}
library(data.table)
library(dtplyr)
cellmarker <- read_excel("data/cell_annotation/Cell_marker_Seq.xlsx")

mouse_lung_marker <-  cellmarker %>% dplyr::filter(species =="Mouse" & tissue_type=="Lung" & cancer_type %in% c("Lung Adenocarcinoma",                "Lung Cancer", "Non-small Cell Lung Cancer", "Normal"))
mouse_lung_marker$cancer_type %>% table()

mouse_lung_marker %>% group_by(cell_name) %>% 
    summarise(marker = str_flatten_comma(marker))
```
