# ExpressionSet

```{r}
library(Biobase)

```

## Assay data

表达值矩阵

```{r}
dataDirectory <- system.file("extdata", package="Biobase")
exprsFile <- file.path(dataDirectory, "exprsData.txt")

exprs <- as.matrix(read.table(exprsFile, header=TRUE, sep="\t",
                              row.names=1,as.is=TRUE))
class(exprs)
dim(exprs)
colnames(exprs)
head(exprs[,1:5])
```

## 表型元数据

```{r}
pDataFile <- file.path(dataDirectory, "pData.txt")
pData <- read.table(pDataFile,row.names=1, header=TRUE, sep="\t")

dim(pData)
colnames(pData)
sapply(pData, class)

rownames(pData)

summary(pData)

all(rownames(pData)==colnames(exprs))
```

元数据

```{r}
metadata <- data.frame(labelDescription= c("Patient gender","Case/control status",
                                           "Tumor progress on XYZ scale"),
                       row.names=c("gender", "type", "score"))
metadata
```

**`Biobase`** 提供了*`AnnotatedDataFrame`* 类来保存表型数据及其元数据

```{r}
phenoData <- new("AnnotatedDataFrame",data=pData, varMetadata=metadata)
phenoData
```

切片

```{r}
head(pData(phenoData))

phenoData[c("A","Z"),"gender"]
pData(phenoData[phenoData$score>0.8,])
```

## 基因元数据及其注释

**`annotation`**和**`AnnotationDbi`**包为元数据包提供了基本的数据操作

```{r}
annotation <- "hgu95av2"
```

## Experiment description

*`MIAME`* ob ject

```{r}
experimentData <- new("MIAME",name="Pierre Fermat",lab="Francis Galton Lab",
                      contact="pfermat@lab.not.exist",
                      title="Smoking-Cancer Experiment",
                      abstract="An example ExpressionSet",
                      url="www.lab.not.exist",
                      other=list(
                        notes="Created from text files"
                        )
                      )
experimentData
```

## 组装ExpressionSet

```{r}
#help("ExpressionSet-class")
miniSet <- ExpressionSet(assayData=exprs)
miniSet

exampleSet <- ExpressionSet(assayData=exprs,
                            phenoData=phenoData,
                            experimentData=experimentData,
                            annotation="hgu95av2")

exampleSet
```

### 切片

```{r}
exampleSet$gender[1:5]
exampleSet$gender[1:5] == "Female"

featureNames(exampleSet)[1:5]
sampleNames(exampleSet)[1:5]
varLabels(exampleSet)
exprs(exampleSet)[1:6,1:5]
```
