project:
  type: book
  output-dir: docs

book:
  title: "Bioinformatics"
  reader-mode: true
  site-url: https://wanganlin00.github.io/Bioinformatics/
  repo-url: https://github.com/Wanganlin00/Bioinformatics
  repo-branch: main
  repo-actions: [edit,issue]
  
  chapters:
    - index.qmd

    - part: sca.qmd
      chapters: 
        - Reads_to_CountMatrix.qmd
        - import.qmd
        - SCE.qmd
        - workflow.qmd
        - QC.qmd
        - normalization.qmd
        - feature_selection.qmd
        - DimensionalityReduction.qmd
        - Clustering.qmd
        - MarkerGeneDetection.qmd
        - CellTypeAnnotation.qmd
        
    - part: "下游分析"
      chapters: 
        - DEGs_Analysis.qmd
        - EnrichmentAnalysis.qmd
        - PseudotimeAnalysis.qmd
        
    - part: "包"
      chapters: 
        - Seurat.qmd
        - AnnotationHub.qmd
        


        
    - part: "基因组学"
      chapters:
        - Biostrings.qmd
        - eQTL.qmd
      
execute:
  cache: true
  message: false
  warning: false

toc: true
toc-depth: 4
number-sections: true
number-depth: 4

code-fold: true
code-tools: true
code-link: true
    
knitr:
  opts_chunk: 
    comment: "#>" 
    collapse: TRUE


format: 
  html: 
    theme: cosmo
    df-print: kable
    callout-appearance: simple
    
editor: visual



