project:
  type: book
  output-dir: docs

book:
  title: "Bioinformatics"
  reader-mode: true
  site-url: https://wanganlin00.github.io/Bioinformatics/
  repo-url: https://github.com/Wanganlin00/Bioinformatics
  repo-branch: main
  repo-actions: [edit,issue]
  
  chapters:
    - index.qmd
    
    - part: "Upstream Analysis"
      chapters: 
        - Seq_to_Matrix.qmd

    - part: "Single-Cell Analysis with Bioconductor"
      chapters: 
        - intro.qmd
        - import.qmd
        - SCE.qmd
        - workflow.qmd
        - QC.qmd
        - normalization.qmd
        - feature_selection.qmd
        - DimensionalityReduction.qmd
        - Clustering.qmd
        - MarkerGeneDetection.qmd
        - CellTypeAnnotation.qmd
        
    # - part: "SingleR"
    #   chapters: 
    #     - SingleR.qmd
        
    - part: "Seurat"
      chapters: 
        - Seurat.qmd
        
    - part: "DESeq2"
      chapters: 
        - TranscriptomicsDownstreamAnalysis.qmd
        
     # - part: "clusterProfiler"
     # - part: "monocle"
        
    - part: "其他"
      chapters: 
        - genomics.qmd

      
execute:
  cache: true
  error: true
  message: false
  warning: false

toc: true
toc-depth: 4
number-sections: true
number-depth: 4

knitr:
  opts_chunk: 
    comment: "#>" 
    collapse: TRUE


format: 
  html: 
    theme: cosmo
    df-print: kable
    code-fold: true
    code-tools: true
    code-link: true
    html-math-method: katex
    callout-appearance: simple
    
editor: visual



