# 细胞类型注释

利用先验信息为未表征的scRNA-seq数据集分配意义，也就是将新数据集中的细胞与已知细胞类型的精选参考谱进行比较，将每个新细胞分配给与其表达谱最相似的参考类型。

最明显的先验信息来源是与特定生物过程相关的精选基因集，例如，基因本体论 （Gene Ontology，GO） 或京都基因与基因组百科全书 （Kyoto Encyclopedia of Genes and Genomes，KEGG）。 或者，直接将单细胞表达谱与已发表的参考数据集进行比较，其中每个样本或细胞都已经由领域专家用其假定的生物学状态进行注释。

[SingleR](https://bioconductor.org/packages/3.18/bioc/html/SingleR.html)是自动注释方法的一种实现，可以被认为是最近邻分类的稳健变体。

基于具有最高Spearman rank correlations的参考样本为细胞分配标签注释， 仅使用参考数据中标签之间的成对比较确定的标记基因的并集来关注细胞类型之间的相关差异（默认为 0.8）。它还可以选择对每个细胞执行微调步骤，其中仅用最高分标签的标记基因重新计算标签子集相关性。这旨在通过消除其他标签的不相关标记的噪声来解决这些标签之间的任何歧义。

更多细节 [Assigning cell types with SingleR](https://bioconductor.org/books/release/SingleRBook/){style="color:red"}

## 根据参考数据集

### 公共数据集

[celldex](https://bioconductor.org/packages/3.18/data/experiment/html/celldex.html) 包含许多精选的参考数据集，这些数据集主要由分选细胞类型的大量 RNA-seq 或微阵列数据组装而成

`BlueprintEncodeData`参考最适合不需要精细分辨率的混合样品， 特别适用于需要快速易于解释的标签的情况。 它提供了不错的免疫细胞颗粒度，尽管不包含更精细的单核细胞和树突状细胞亚型。

调用`SingleR()`使用`BlueprintEncodeData`参考集中的主要细胞类型标签对`sce.pbmc`注释，返回一个`DataFrame`，每行对于一个测试集中的细胞和其注释标签， 参考集`ref=`需要包含测试集`test=`中预期的细胞类型

使用每个细胞和标签分数的热图检查结果。理想情况下，每个细胞在一个标签中相对于所有其他标签都应表现出高分，表明对该标签的分配是明确的。

将细胞类型与聚类结果进行比较，以确定每个聚类的身份。

### 自定义参考集
